# Production
baseURL = "/"

languageCode = "en-us"
DefaultContentLanguage = "en"
title = "Upkip Documentation"
theme = "c8ydocs"
paginate = 12
# canonifyurls = false
# publishDir = "public/site"
# googleAnalytics = "UA-xxxxxxxx-x"
summaryLength = 30
buildFuture = true

relativeURLs = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.highlight]
      style = "solarized-dark256"

[author]
  name = "Carlos Ceia @ Cumulocity"



[params]
  custom_css = ["css/custom_style.css"]
  # Customize date format use to render blog post date, categories and other
  # You must use date format used by Go Time package https://golang.org/pkg/time/
  # Months (not work with short month like "jan", "feb", etc) are translated if translation exists on i18n folders
  # Default format is: January 2, 2006
  # dateFormat = "2 January 2006"

  description = "Resources for connecting your machines and devices to the Internet of Things"
  # Display thumbnail image of each post on index pages (false: disabled, true: enabled)
  thumbnailImage = true

  logo = "images/upkip-logo.svg"

  guidesRedirect = "/admin/overview"

  # Your favicon path, default is "/favicon.png"
  favicon = "/favicon.ico"

# Customize
  [params.footer]
    copyright = "InterConsult Bulgaria LTD | All rights reserved"

[outputs]
  home = ["HTML", "RSS","JSON"]